### ISSUE TITLE
Replaying notifications misses events with identical request

### ISSUE THREAD

**Issue by victoria-cherkas** [ecmwf/aviso#7]
### What happened?

Our aviso is being notified of new data from ECPDS - Destination is a s3 bucket in EWC. 
Data for a single forecast for lead time = 0 is provided in two different files (one containing constants, the other with variable fields). In real time I aviso receives two events with same request details but different location. eg

```
Notification received: {'event': 'dissemination', 'request': {'destination': 'X', 'date': '20230704', 'target': 'P1', 'class': 'od', 'expver': '0001', 'domain': 'g', 'time': '12', 'stream': 'oper', 'step': '0'}, 'location': 's3://input/X011111'}
Notification received: {'event': 'dissemination', 'request': {'destination': 'X', 'date': '20230704', 'target': 'P1', 'class': 'od', 'expver': '0001', 'domain': 'g', 'time': '12', 'stream': 'oper', 'step': '0'}, 'location': 's3://input/X022222'}
```

However when I replay the notifications (`aviso listen --from 2020-01-20T00:00:00.0Z`) I only get one of the above notifications replayed.

part of aviso config.yaml:
```
listeners:
  - event: dissemination
    request:
      destination: bucket-in-ewc
      class: od
      expver: 0001
      domain: g
      stream: [oper, scda]
```

### What are the steps to reproduce the bug?

Send two notifications with same event details but different s3 location. Replay the notifications and verify if both are received.

### Version

0.11.1

### Platform (OS and architecture)

ubuntu-18.04 

### Organisation

MeteoSwiss
